### ISSUE TITLE
publish npm fetchable package automatically

### ISSUE THREAD

**Issue by WhoIsSethDaniel** [bscan/PerlNavigator#10]
Now that there is an automatic build can it also publish the npm package whenever a build occurs?

For now the neovim installer depends on the npm package so any changes to the code should be published this way also.

I will also look at using the binaries that are being built. One reason I might not use the binaries is because the neovim installer has a very nice feature where it can show all the configuration elements *iff* there is a package.json in the installation directory. This gets lost if I use the binaries.

**Comment by ketbra** [comment]
Would it be helpful if I added the package.json file to the zip archive containing the executable, or is the package.json parsing only part of the npm installation method logic?

As for automatic NPM package publishing, we are looking into that as well.  The eventual plan is to have our tests, NPM publishing, binary building, and VS Code Marketplace publishing all occur as part of release creation.

**Comment by WhoIsSethDaniel** [comment]
@ketbra I think packaging the packages.json would likely work. I'll test it on my end before saying anything definitive.

**Comment by bscan** [comment]
This is now complete. I still need to add tests and vscode marketplace pushing, but the release workflow is now publishing to NPM. Thanks!
