### ISSUE TITLE
lsp-mode defaults to using PerlNavigator

### ISSUE THREAD

**Issue by titanofold** [bscan/PerlNavigator#103]
Just wanted to note that there are no special steps to getting PerlNavigator working with Emacs' lsp-mode. It's only necessary to have PerlNavigator installed, and lsp-mode will try to find the executable in PATH. Alternatively, `lsp-perlnavigator-executable` can be set if the desired perlnavigator is not in the path, such as:

```emacs-lisp
(use-package lsp-mode
  ...
  :custom (lsp-perlnavigator-executable (expand-file-name "~/path/to/perlnavigator))
  ...)
```

PLS and Perl::LanguageServer have lower priorities and will only be selected if PerlNavigator is not found.

Thank you for your work on this project!

**Comment by bscan** [comment]
Thanks for filing the issue. I updated the Readme to include this information as well. I didn't realize Perl Navigator had the highest `priority`, but that's good to know as well.
