### ISSUE TITLE
VSCode - Seem unable to get perltidy to trigger

### ISSUE THREAD

**Issue by PaulGWebster** [bscan/PerlNavigator#104]
Good day,

I managed to configure everything as I would like with critic and perlimports, the only issue I face is with perltidy, even though I can use it from command line with no issue and I have a fairly standard ~/.perltidyrc ( I even tried removing it just incase ). 

But no matter what I do, be it saving the file or looking for perltidy in the 'power menu'(sp? - ctrl shift p) I cannot get perltidy to trigger, I checked for any extensions that could possible be interfering and can find nothing.

My config has the following:

<pre>
    "perlnavigator.enableWarnings": true,
    "perlnavigator.perlcriticEnabled": true,
    "perlnavigator.perlcriticProfile": "~/.perlcriticrc",
    "perlnavigator.perltidyEnabled": true,
    "perlnavigator.perltidyProfile": "~/.perltidyrc",
    "perlnavigator.perlimportsLintEnabled": true,
    "perlnavigator.perlimportsTidyEnabled": true,
    "perlnavigator.perlimportsProfile": "~/.perlimports.toml"
</pre>
    
   Is anyone able to offer any insight?

**Comment by bscan** [comment]
Closing for now, but feel free to re-open if I misunderstood.
