### ISSUE TITLE
File::Find dies when a duplicate file is found

### ISSUE THREAD

**Issue by drgrice1** [bscan/PerlNavigator#115]
It seems that `follow_skip => 2` needs to be added around line 27 of `server/src/perl/lib_bs22/ModHunter.pl`.  I am seeing an issue on Ubuntu 22.04 where `/usr/share/javascript/bootstrap4/css/bootstrap.min.css` is encountered a second time.  This results in `ModHunter` failing.

**Comment by bscan** [comment]
Thanks @drgrice1! I haven't seen this happen before, it must be related to some symlink layout or series of nested directories. It looks like a safe fix though.  It's now available as version 0.8.3 in the vscode marketplace. I need to do some testing on the NPM version and will push to NPM soon as well. Thank you for reporting the issue and for finding a fix.

**Comment by drgrice1** [comment]
Thanks.  Looking forward to the next release.
