### ISSUE TITLE
Publish new release to npm

### ISSUE THREAD

**Issue by mrsdizzie** [bscan/PerlNavigator#118]
I see in the changelog there are entries for different 0.8 releases but the last release on npm is `0.7.13`. Would it be possible to publish the latest 0.8 release on npm? 

Specifically looking to try the `Allow disabling "perl -c"` feature.

Appreciate the work, thanks!

**Comment by WhoIsSethDaniel** [comment]
There are a few more useful things that were just merged. I hope this can be done soon.

**Comment by bscan** [comment]
Thanks for the nudge. I had some additional development needed due to the recent move to webpack. A few changes were needed to make the NPM binaries bundle the content in a similar way. Version 0.8.9 is now available on NPM

**Comment by mrsdizzie** [comment]
Amazing thanks I really appreciate it! This request is mainly because Mason for neovim [uses npm](https://github.com/mason-org/mason-registry/pull/5264) as the Perl Navigator source.
