### ISSUE TITLE
Does not working on Windows.

### ISSUE THREAD

**Issue by mattn** [bscan/PerlNavigator#12]
* Windows 11 64bit
* Visual Studio Code or Vim
* Perl v5.32.1

![image](https://user-images.githubusercontent.com/10111/163680358-8e768e3a-666a-445c-a84e-2ae52dd1143b.png)

![image](https://user-images.githubusercontent.com/10111/163680346-c3bbc55c-0f83-4f72-9897-8e692ce097cc.png)

Could you help me?

**Comment by bscan** [comment]
Sure, perhaps you don't have modules named "Set::"? There are some other tests we could do. Try doing a "Goto Definition" (ctrl+click) on the variable $i on line 12. It should jump you to line 7. 

Alternatively, can you check the log (View->Output and then change the output to "Perl Navigator LSP") to see if it says anything helpful. You might want to restart VSCode before checking the log in case it has lots of repeated diagnostics.

**Comment by mattn** [comment]
Yes, Go to definition is working fine. But completion does not. `textDocument/completion` is not appear in the log.

**Comment by bscan** [comment]
If you aren't seeing the `Sending request 'textDocument/completion`, it sounds like vscode client is not sending the request to the server. You can also turn on verbose server logs with "perlnavigator.trace.server": "verbose", but if the issue is on the client side, it might not help much. I just declared my $foo = 1, saved the file, and tried typing print $foo. (Saving the file is not strictly required, but makes sure the $foo definition is processed before continuing). 

On Windows 11, I see the following:

```
[Trace - 12:42:31 PM] Sending request 'textDocument/completion - (124)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/brian/Documents/Workspace/Sandbox.pl"
    },
    "position": {
        "line": 4,
        "character": 1
    },
    "context": {
        "triggerKind": 2,
        "triggerCharacter": "$"
    }
}


[Trace - 12:42:31 PM] Received response 'textDocument/completion - (124)' in 1ms.
Result: {
    "items": [
        {
            "label": "$foo",
            "textEdit": {
                "newText": "$foo",
                "range": {
                    "start": {
                        "line": 4,
                        "character": 0
                    },
                    "end": {
                        "line": 4,
                        "character": 1
                    }
                }
            },
            "kind": 6,
            "sortText": "1$foo"
        }
    ],
    "isIncomplete": false
}
```

**Comment by mattn** [comment]
Hmm, after installation of Perl::Critic, it works on VSCode. But nothing works on vim-lsp.

**Comment by bscan** [comment]
Nice, glad it's working for you in vscode. Support for vsode has certainly been my top priority. For vim, I haven't seen it working in vim-lsp or ALE, but a few people have used it in Neovim. It can be installed via the lsp-installer plugin https://github.com/williamboman/nvim-lsp-installer , or used with COQ: https://climatechangechat.com/fast_as_fuck_perl_language_server_and_completion.html

**Comment by mattn** [comment]
Hi, now I had figured out what was wrong.

https://github.com/prabirshrestha/vim-lsp/pull/1302

vim-lsp does not reply the request of workspaceFolders from servers.

![screenshot](https://user-images.githubusercontent.com/10111/163722646-f04c302c-939d-4475-871a-e047744bab58.gif)

I'll add perlnavigate to vim-lsp-settings. Thanks.

https://github.com/mattn/vim-lsp-settings/pull/556
