### ISSUE TITLE
Set logging = true for all editors

### ISSUE THREAD

**Issue by WhoIsSethDaniel** [bscan/PerlNavigator#122]
Discussed in #120 (starting [here](https://github.com/bscan/PerlNavigator/issues/120#issuecomment-2023957294)).

Perhaps make logging `true` (or "on") by default for all editors. Currently it is only on by default for vs code.

**Comment by WhoIsSethDaniel** [comment]
#123 the logging is turned on. I don't know what else can be done.

**Comment by bscan** [comment]
Thanks for the contribution @WhoIsSethDaniel. This is now available in npm in version 0.8.9
