### ISSUE TITLE
warning on shebang

### ISSUE THREAD

**Issue by Reissner** [bscan/PerlNavigator#138]
My file starts with 
```
#!/usr/bin/env perl
```
and right this causes a warning
```
Syntax: Attempt to call undefined import method with arguments ("-except" ...) via package "namespace::autoclean" (Perhaps you forgot to load the package?) at /usr/lib/perl5/vendor_perl/5.40.0/DateTime/Locale/Util.pm line 5.
```

I think there should be no warning. 
And I suspect the warning is not correct either.

**Comment by bscan** [comment]
Hi @Reissner. This is a new issue when using Perl Navigator with Perl 5.40. @oalders has the solution with this pull request, I just need to accept it, do some testing, and put out a new release. I should hopefully get to this soon. Thanks!     https://github.com/bscan/PerlNavigator/pull/135

**Comment by oalders** [comment]
For what it's worth, I have been running that patch locally since I made the PR and I haven't seen any issues with it. I had looked at writing a test for it, but that appeared to be a non-trivial task.

**Comment by bscan** [comment]
Sounds good, thanks for the fix @oalders. Full disclosure, I haven't done any testing with Perl 5.40 yet but let me know if anything else breaks. One of these days, I'd like to set up testing that allows the matrix of tests across versions and operating systems.

**Comment by bscan** [comment]
The fixed version is available in the vscode marketplace and on NPM, both as version 0.8.15
