### ISSUE TITLE
Crashes when used with Emacs lsp-mode

### ISSUE THREAD

**Issue by KikyTokamuro** [bscan/PerlNavigator#2]
Versions:
```
node - 17.3.0
tsc - 4.5.5
emacs - 27.2
perl - 5.34.0
```

The configuration for enabling the new lsp server was taken from your comment on reddit (https://www.reddit.com/r/perl/comments/suamcf/comment/hxg3evr/?utm_source=share&utm_medium=web2x&context=3)

Emacs config:
```elisp
(use-package cperl-mode
  :ensure t
  :init (defalias 'perl-mode 'cperl-mode)
  :config
  (setq cperl-highlight-variables-indiscriminately t
	cperl-indent-level 4
        cperl-tab-always-indent nil
        cperl-continued-statement-offset 0
        cperl-indent-parens-as-block t
        cperl-close-paren-offset -4
        cperl-electric-keywords t
        cperl-label-offset 0)
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection '("node" "/home/kiky/work/PerlNavigator/server/out/server.js" "--stdio"))
		    :major-modes '(cperl-mode perl-mode)
		    :priority 10
		    :server-id 'perl-ls))
  :hook
  (cperl-mode . lsp)
  (cperl-mode . (lambda () (add-hook 'before-save-hook 'perltidy-buffer))))
```

lsp-log:
```
Command "perl -MPerl::LanguageServer -e Perl::LanguageServer::run -- --port 13603 --version 2.1.0" is present on the path.
Command "node /home/kiky/work/PerlNavigator/server/out/server.js --stdio" is present on the path.
Found the following clients for /home/kiky/work/perl/sendmail.pl: (server-id perl-language-server, priority -1), (server-id perl-ls, priority 10)
The following clients were selected based on priority: (server-id perl-ls, priority 10)
```

perl-ls::stderr:
```
/home/kiky/work/PerlNavigator/server/out/utils.js:11
    settings.includePaths.forEach(path => {
                          ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at getIncPaths (/home/kiky/work/PerlNavigator/server/out/utils.js:11:27)
    at perlcompile (/home/kiky/work/PerlNavigator/server/out/diagnostics.js:15:60)
    at validatePerlDocument (/home/kiky/work/PerlNavigator/server/out/server.js:155:52)
```

**Comment by ketbra** [comment]
I'm Brian's coworker that got this working in Emacs.  I was able to reproduce your problem with an older vsix file I unpacked, but I couldn't reproduce the problem after building from the latest source.  Are you still getting this issue if you pull down the latest source and rebuild?  Perhaps Brian fixed something, but if that doesn't resolve your problem then I can try to track down what's going on in the older build.

**Comment by KikyTokamuro** [comment]
> I'm Brian's coworker that got this working in Emacs. I was able to reproduce your problem with an older vsix file I unpacked, but I couldn't reproduce the problem after building from the latest source. Are you still getting this issue if you pull down the latest source and rebuild? Perhaps Brian fixed something, but if that doesn't resolve your problem then I can try to track down what's going on in the older build.

I clone the repository again, and tried it, the error remained the same:
```
Process perl-ls stderr finished
/home/kiky/work/PerlNavigator/server/out/utils.js:11
    settings.includePaths.forEach(path => {
                          ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at getIncPaths (/home/kiky/work/PerlNavigator/server/out/utils.js:11:27)
    at perlcompile (/home/kiky/work/PerlNavigator/server/out/diagnostics.js:15:60)
    at validatePerlDocument (/home/kiky/work/PerlNavigator/server/out/server.js:155:52)
```

List of commands that I have run:
```
git clone https://github.com/bscan/PerlNavigator
cd PerlNavigator/
npm install
cd server/
npm install
tsc
```

**Comment by ketbra** [comment]
Hi Daniil,

I made a small change to how the default settings are created.  Can you please try grabbing the source now?  During startup there was a time when the default settings may not have been applied yet.  I'm hoping that the change I made causes the default settings to apply immediately, so includePaths should default to an empty array and hence prevent the error you are seeing.

Thanks,
Matt

**Comment by KikyTokamuro** [comment]
The last changes helped, now everything works fine and without errors.

Thank you, you've done a great job!
