### ISSUE TITLE
Installation for other editors - missing cd command?

### ISSUE THREAD

**Issue by HaraldJoerg** [bscan/PerlNavigator#38]
The installation instructions at https://github.com/bscan/PerlNavigator#installation-for-other-editors didn't work for me after the most recent change:  I had to add a `cd server` before running `tsc` (the command was there in older versions of the instructions)

I am not at all familiar with typescript build processes, so I don't know whether the command has been accidentally deleted or whether my workaround was just pure luck - if that's the correct fix I can prepare a PR

**Comment by nugged** [comment]
Thanks.

Indeed. It took some precious amount of time to figure out this too :(

**Comment by bscan** [comment]
This should now be resolved with #70. Also, the perlnavigator is now installable direct from npm, which should make the install process easier.
```
npm install -g perlnavigator-server
```

Thanks!
