### ISSUE TITLE
Can the npm package be updated to latest version? 

### ISSUE THREAD

**Issue by Daz9** [bscan/PerlNavigator#40]
I recently managed to get PerlNavigator working on nvim quite easily using mason.nvim. 

However, Mason pulls the LSP from npm instead of git. Currently, the npm package uses version 0.2.8. 

Is there any chance the npm package be updated to the most recent version? 

I did try to edit the installation instructions in mason.nvim to download the LSP from git but I haven't been able to get it working yet so npm seems to be the most straightforward method.

**Comment by WhoIsSethDaniel** [comment]
With the large, recent change(s) is it possible that this can happen?  Thank you.

**Comment by oalders** [comment]
It would be great to see this. 😄

**Comment by bscan** [comment]
Yes, hopefully I will finish this up this weekend. There is currently a github workflow (see https://github.com/bscan/PerlNavigator/blob/main/.github/workflows/release.yml)  that is able to build binaries for each release. I need to get this to publish to npm as well, and then start publishing regular official releases. Thanks for the ping, I believe this is a good idea, especially with the various recent updates.

**Comment by bscan** [comment]
I published the latest version to npm, and updated the release workflow to include an npm step. Now the release workflow includes building the binaries and publishing to npm, but does not yet publish to the vscode marketplace or put anything on CPAN. Thanks for continuing to push on this, it should make the Navigator more easily accessible to more people.

**Comment by WhoIsSethDaniel** [comment]
Thanks @bscan.  

Apologies if you are still working on this, but 0.3.3 installed fine and runs great. However 0.3.6 does not install. I haven't looked at it yet, but  did something change between those two versions?

**Comment by bscan** [comment]
Thanks for trying it out! Perhaps there is a bug. Those should be the same version, I simply added a README and bumped the version a few times to exercise the release functionality. I'll try installing as well, but is there a specific error that it gives?

**Comment by WhoIsSethDaniel** [comment]
I'm just starting to dig in to this. The error I get from `mason.nvim` (the neovim plugin that installs LSP servers and other third-party dependencies) is:
```
[ERROR Sun 13 Nov 2022 01:43:48 PM CST] ...plugins/opt/mason.nvim/lua/mason-core/installer/init.lua:154: Installation failed for Package(name=perlnavigator) error="...plugins/opt/mason.nvim/lua/mason-core/installer/init.lua:121: Cannot write Node exec wrapper for path \"node_modules/perlnavigator-server/out/server.js\" as it doesn't exist."
```
I'm not terribly familiar with `npm` so I'm still working on installing the `perlnavigator` package directly to see how 0.3.6 differs from 0.3.3

**Comment by WhoIsSethDaniel** [comment]
okay, I installed `perlnavigator` version 0.3.6 and it is indeed missing the directory mentioned above (`node_modules/perlnavigator-server/out`). Whereas the 0.3.3 package has this directory (as well as the `server.js` file in that directory).

**Comment by WhoIsSethDaniel** [comment]
The package is being installed using `npm install perlnavigator@<version>`.

**Comment by bscan** [comment]
Thanks! The github workflow was missing a typescript compilation step. I had pushed 0.3.3 manually, which is why that version worked. Can you retry with version 0.3.7?

**Comment by WhoIsSethDaniel** [comment]
0.3.7 works great!

**Comment by bscan** [comment]
Awesome, thanks for the help on this one.
