### ISSUE TITLE
package for npm

### ISSUE THREAD

**Issue by WhoIsSethDaniel** [bscan/PerlNavigator#5]
Is there any chance to package this up for whatever repository `npm` uses? I was looking at the other typescript servers that nvim-lspconfig and nvim-lsp-installer supports and all of them require just `npm install <something>`. Typically the &lt;something&gt; would be, say, `perl-navigator-server` or something like that.

Any chance of this? If not I'm sure it can be worked around, but will make it more difficult, I think.

**Comment by bscan** [comment]
Sure, this is a great idea. I've never published on npm before, but they made it shockingly easy. I just created an account and pushed the server as is. `npm install perlnavigator-server` pulls down the server (or add -g for a global install). I did test the installation through this method gives a usable server, but I haven't tested any more than that. Take a look, and I'll kick the tires some more as well. Thanks for the suggestion, and for pushing this forward.
