### ISSUE TITLE
Add $workspaceFolder variable expansion to perltidyProfile setting

### ISSUE THREAD

**Issue by Strongbeard** [bscan/PerlNavigator#52]
It would be helpful to be able to use the `$workspaceFolder` variable in `perlnavigator.perltidyProfile` similarly to how `perlnavigator.includePaths` currently works.

There was an attempt to do this with a commented version of the `getTidyProfile()` function the end of `formatting.ts`, but it seems to have been put on hold due to difficulty dealing with multi-root workspaces. Is it possible to enable this for only single-root workspaces and add an error log and/or documentation that it will not work for multi-root workspaces as a short-term work around?

https://github.com/bscan/PerlNavigator/blob/6ba380005b103e65cc86a3b4f96e1e391a51c000/server/src/formatting.ts#L113-L144

**Comment by bscan** [comment]
Thanks for the report. Currently, the perlcritic profile does this substitution as well and uses the first folder in a multi-root workspace. I suppose the ideal solution would be looping over all the folders looking for the first valid profile. However, I suspect the combination of multi-root workspaces and $workspaceFolder specified tidy profiles are a pretty rare occurrence. I just added support for this and will push the updates to the marketplace this evening. Thanks!
