### ISSUE TITLE
Add ability to set perlcritic --theme EXPRESSION

### ISSUE THREAD

**Issue by JohnC32** [bscan/PerlNavigator#58]
Within our .perlcriticrc file we have several themes and it would be helpful to be able to specify a desired theme for perlcrittic

Note, I'm using the perl navigator with Emacs language server, so I suspect we'll also need to update: https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-perlnavigator.el to support a theme option.

Thanks

**Comment by bscan** [comment]
Seems reasonable. I could probably add variety of critic options that include theme, severity, include patterns, and exclude patterns. This would especially be helpful for people without a profile. Although, if you already have a .perlcriticrc file setup, wouldn't it be easier to simply specify the theme in there?

**Comment by JohnC32** [comment]
In our .perlcriticrc, we have:

     theme = projname_strict
     
     ....
     [BuiltinFunctions::ProhibitShiftRef]
     add_themes                           = projname_basic projname_strict
     
     [BuiltinFunctions::RequireBlockGrep]
     add_themes                           = projname_strict
     
     ....

In our build system, we require "perlcritic --theme projname_basic" pass. In editors, etc. we tend to use projname_strict, unless we're making a minor change to the file, then we use projname_basic. Thus, having the ability to switch would help in our workflow.

I also think it's a good idea to add the other options. We'd probably leverage them.

Thanks

**Comment by bscan** [comment]
Hi @JohnC32 , these features are now all in the Navigator. The settings are: "perlnavigator.perlcriticSeverity", "perlnavigator.perlcriticTheme", "perlnavigator.perlcriticExclude", "perlnavigator.perlcriticInclude", and they all correspond to arguments listed at: https://metacpan.org/pod/Perl::Critic 

They aren't yet in `lsp-perlnavigator.el`, but I think that would be straightforward to locally modify. Theme, include, and exclude are all strings, while severity is a number. Let me know if it works for you, and thank you for submitting the issue!
