### ISSUE TITLE
How to display debug output from navigator?

### ISSUE THREAD

**Issue by hakonhagland** [bscan/PerlNavigator#64]
In the source I see lines like this:

https://github.com/bscan/PerlNavigator/blob/31b6d7b4b110821ea7550abb0dde53ebe94e5cd3/server/src/diagnostics.ts#L177

How can I display these log lines from within VS Code?

**Comment by bscan** [comment]
Hi @hakonhagland, you can see the output in the console "output" window by selecting the "Perl Navigator" in the drop down on the right. This issue has an image showing the location: 
https://github.com/bscan/PerlNavigator/issues/3#issuecomment-1049391183 

Assuming you're debugging the critic wrapper, you could also pipe your source code directly into the wrapper with something like `cat myFile.pl | perl criticWrapper.pl` (https://github.com/bscan/PerlNavigator/blob/main/server/src/perl/criticWrapper.pl) and the resulting violations will be displayed in stdout. 

Criticwrapper.pl has no internal dependencies, so you could just download just the single file and drop it anywhere for testing. Thanks for diving in here.

**Comment by hakonhagland** [comment]
> you can see the output in the console "output" window by selecting the "Perl Navigator" in the drop down on the right.

Yes that works :smiley:
