### ISSUE TITLE
help at getting perlnavigator working

### ISSUE THREAD

**Issue by amonull** [bscan/PerlNavigator#66]
perl version: 5.36.0
perl path: /ur/bin/perl
ide/text editor: neovim, lunarvim. vscode
install method: Mason, vscode marketplace
setup method: lspconfig

hi, i wanted to start learning perl and wanted to get perlnavigator working with lunarvim and lsp but i can't get the completion to work.

i already opened an issue on lunarvim for this ages ago but couldn't find an answer to my problem i also tried to get perlnavigator working on neovim with lspconfig and the default config in the README however that also didn't work, i have also tried to download the perlnavigator extension for vscode and still didn't have any completion for  perl.

i think perl navigator is working since it does give warnings like the one below:
![image](https://user-images.githubusercontent.com/90932550/227714039-c331174d-69d6-40d7-8c46-f3c27fa0e251.png)

i also had the same warnings come up in the vscode extension. 

Again this is the first time i am using perl so is there more i have to configure or add to get the completion working.

**Comment by WhoIsSethDaniel** [comment]
What completion plugin are you using for neovim? Are you using the builtin completion? I'd recommend [nvim-cmp](https://github.com/hrsh7th/nvim-cmp). It will require a small number of other plugins, but that should be documented on the github site. Once it is setup properly you will get completions. I can guarantee that because that's what I have setup.

**Comment by amonull** [comment]
i am using nvim-cmp with the config from https://github.com/LunarVim/Neovim-from-scratch/blob/master/lua/user/cmp.lua (pasted below)
```
local cmp_status_ok, cmp = pcall(require, "cmp")
if not cmp_status_ok then
  return
end

local snip_status_ok, luasnip = pcall(require, "luasnip")
if not snip_status_ok then
  return
end

require("luasnip/loaders/from_vscode").lazy_load()

local check_backspace = function()
  local col = vim.fn.col "." - 1
  return col == 0 or vim.fn.getline("."):sub(col, col):match "%s"
end

--   פּ ﯟ   some other good icons
local kind_icons = {
  Text = "",
  Method = "m",
  Function = "",
  Constructor = "",
  Field = "",
  Variable = "",
  Class = "",
  Interface = "",
  Module = "",
  Property = "",
  Unit = "",
  Value = "",
  Enum = "",
  Keyword = "",
  Snippet = "",
  Color = "",
  File = "",
  Reference = "",
  Folder = "",
  EnumMember = "",
  Constant = "",
  Struct = "",
  Event = "",
  Operator = "",
  TypeParameter = "",
}
-- find more here: https://www.nerdfonts.com/cheat-sheet

cmp.setup {
  snippet = {
    expand = function(args)
      luasnip.lsp_expand(args.body) -- For `luasnip` users.
    end,
  },
  mapping = {
    ["<C-k>"] = cmp.mapping.select_prev_item(),
		["<C-j>"] = cmp.mapping.select_next_item(),
    ["<C-b>"] = cmp.mapping(cmp.mapping.scroll_docs(-1), { "i", "c" }),
    ["<C-f>"] = cmp.mapping(cmp.mapping.scroll_docs(1), { "i", "c" }),
    ["<C-Space>"] = cmp.mapping(cmp.mapping.complete(), { "i", "c" }),
    ["<C-y>"] = cmp.config.disable, -- Specify `cmp.config.disable` if you want to remove the default `<C-y>` mapping.
    ["<C-e>"] = cmp.mapping {
      i = cmp.mapping.abort(),
      c = cmp.mapping.close(),
    },
    -- Accept currently selected item. If none selected, `select` first item.
    -- Set `select` to `false` to only confirm explicitly selected items.
    ["<CR>"] = cmp.mapping.confirm { select = true },
    ["<Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif luasnip.expandable() then
        luasnip.expand()
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      elseif check_backspace() then
        fallback()
      else
        fallback()
      end
    end, {
      "i",
      "s",
    }),
    ["<S-Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end, {
      "i",
      "s",
    }),
  },
  formatting = {
    fields = { "kind", "abbr", "menu" },
    format = function(entry, vim_item)
      -- Kind icons
      vim_item.kind = string.format("%s", kind_icons[vim_item.kind])
      -- vim_item.kind = string.format('%s %s', kind_icons[vim_item.kind], vim_item.kind) -- This concatonates the icons with the name of the item kind
      vim_item.menu = ({
        nvim_lsp = "[LSP]",
        luasnip = "[Snippet]",
        buffer = "[Buffer]",
        path = "[Path]",
      })[entry.source.name]
      return vim_item
    end,
  },
  sources = {
    { name = "nvim_lsp" },
    { name = "luasnip" },
    { name = "buffer" },
    { name = "path" },
  },
  confirm_opts = {
    behavior = cmp.ConfirmBehavior.Replace,
    select = false,
  },
  window = {
    documentation = {
      border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
    },
  },
  experimental = {
    ghost_text = false,
    native_menu = false,
  },
}

```

recently i started getting this error on perl files only and completion on vanilla neovim works with other lsp like pyright and bashls.

error:
![image](https://user-images.githubusercontent.com/90932550/228521900-087d5989-cfa5-4b21-8fea-cb0b016de272.png)

**Comment by WhoIsSethDaniel** [comment]
I'll use the LunarVim config and see if I can get it working. Or if I can replicate your problem.

**Comment by WhoIsSethDaniel** [comment]
It looks like [nvim-basic-ide](https://github.com/LunarVim/nvim-basic-ide) is the same project but different somehow? It's maintained by the same user and is recommended in the `Neovim-from-Scrath` README. I don't know if it will help, but may be worth a shot if all other attempts fail.

**Comment by WhoIsSethDaniel** [comment]
Ok, I started using the `Neovim-from-scratch` config. I made one change and it immediately started working for Perl, including completion. The change I made was I added 'perlnavigator' to the list of `servers` in `lua/user/lsp/mason.lua`.

**Comment by WhoIsSethDaniel** [comment]
@amonull if you are still using `Neovim-from-scratch` I would suggest you start, like I did, with a fresh install and perform the change I mentioned. Then start adding in any other changes you have made until it breaks. You will then know what is causing the problem. The takeaway is that completion works fine and is pretty simple to get working with a vanilla install of `Neovim-from-scratch`.

**Comment by amonull** [comment]
i just copied the `neovim-from-scratch` repo and moved it to `~/.config/nvim` without making any changes other than adding `perlnavigator` to server list however i still am not getting any lsp completion.

example of what it looks like:
![image](https://user-images.githubusercontent.com/90932550/228655765-c6243371-4547-4bfd-b9cb-66b2d39c12e0.png)
 LspInfo:
![image](https://user-images.githubusercontent.com/90932550/228655843-06e0ba3f-3756-4e0c-978b-8e8305a3042f.png)

lsp is running fine as usual and still gives errors the only problem is completion. i am also getting the exact same results with lunarVim where the lsp is running and i am getting syntax errors shown to me but no completion.

**Comment by bscan** [comment]
Thanks @WhoIsSethDaniel for jumping in here, the vim family of editors is not my strong suit.

@amonull, another thing to watch out for is the relatively targeted set of items in the Perl Navigator autocomplete. I like the autocomplete feature, as it tries to provide the most relevant suggestions and some cases may not have any suggestions at all. In your screenshot for example, I wouldn't expect anything since there are no variables or imported packages. However, it should complete in the context of `use File::` and also if you have any `my $foo` variables defined in the file.

**Comment by WhoIsSethDaniel** [comment]
Thanks @bscan.  @amonull if you start with `nvim something.pl` and type:
```
#!/usr/bin/perl

use Moose;
M
```
When you type the "M" it should display completion options. If you then use completion to have it type "Moose", so you have 
this:
```
#!/usr/bin/perl

use Moose;
Moose
```
Type "->" (or even just "-") directly after "Moose" and you'll get a bunch of other completions relating to the Moose module.

**Comment by amonull** [comment]
thank you @bscan  and @WhoIsSethDaniel for the help in me understanding perlnavigator.

i thought that using single letters would start giving me lsp completion suggestions i didn't realize perl was different in giving structures. everything works fine and has been working fine all along. sorry for my confusion and again thank you both for the help
