### ISSUE TITLE
Tutorial for PN with COQ

### ISSUE THREAD

**Issue by sdondley** [bscan/PerlNavigator#7]
See https://climatechangechat.com/fast_as_fuck_perl_language_server_and_completion.html

**Comment by bscan** [comment]
Nice, this is a great resource for getting the Navigator going. I will add setup instructions for Neovim to the Readme, with a link to your page. One minor correction: the snippets are not coming from the Navigator (although a good idea for me to add). Perhaps they are built in to COQ?

**Comment by sdondley** [comment]
Interesting. I just assumed they were coming from the LS. Maybe COC has it's own library. I'll have to research that.

**Comment by sdondley** [comment]
Ah. So that's what coq.artifacts is. 

https://github.com/ms-jpq/coq_nvim/blob/coq/docs/SNIPS.md
