### ISSUE TITLE
What does it need to support AIX too?

### ISSUE THREAD

**Issue by XSven** [bscan/PerlNavigator#77]
I want to enable the Perl Navigator using a vim-lsp plugin on an AIX system. I am getting the error message

> aix doesn't supported by bash installer

The reason for this error is a missing Perl Navigator release for AIX. What does it need to support AIX too?

**Comment by bscan** [comment]
Hi @XSven. Although there is no binary available for AIX systems, you should be able to build from source by following the instructions here https://github.com/bscan/PerlNavigator#installation-for-other-editors .

**Comment by bscan** [comment]
Closing this ticket for now. I also added more options to the README for installation (e.g. `npm install -g perlnavigator-server`). Let me know if anything doesn't work correctly on AIX. Thanks!
