### ISSUE TITLE
Perl import not detecting local package

### ISSUE THREAD

**Issue by Vic-M** [bscan/PerlNavigator#86]
Perl imports doesn't seem able to pick my local packages and always recommends removing them.

![image](https://github.com/bscan/PerlNavigator/assets/32042587/436f2a8f-502f-4787-ab67-75c2c1e29a74)

reference code: https://gitlab.com/vmatassa/perl_import_test

perl version: v5.32.1
perl navigator version: 0.5.9
App::perlimports version: 0.000052

**Comment by WhoIsSethDaniel** [comment]
Hi @Vic-M . This may be more appropriate to ask on the perlimports issues page: https://github.com/perl-ide/App-perlimports/issues

**Comment by oalders** [comment]
@bscan based on the discussion in the linked issue, I think you can close this one.
