### ISSUE TITLE
Use a code formatter like Prettier

### ISSUE THREAD

**Issue by IAKOBVS** [bscan/PerlNavigator#95]

**Comment by bscan** [comment]
Sure, this is a good idea. VScode comes with a built-in formatter as well, but I'm happy to use Prettier instead, and make a habit of formatting. I just configured Prettier in my vscode with the following settings. I think it works well and is relatively gentle with the suggested changes. Thanks!
``` 
"prettier.tabWidth": 4,
"prettier.printWidth": 150 
```
