### ISSUE TITLE
autocomplete: keep showing function prototype after selection

### ISSUE THREAD

**Issue by IAKOBVS** [bscan/PerlNavigator#96]
![image](https://github.com/bscan/PerlNavigator/assets/89495599/757f3a2e-e6f2-43db-82ef-1b6c6cb91612)
![image](https://github.com/bscan/PerlNavigator/assets/89495599/359e38b1-a016-4d8f-b240-ab4b504ba596)
![image](https://github.com/bscan/PerlNavigator/assets/89495599/9d9f4675-d145-4a5d-9a14-f3b799c2955c)

Expected behaviour:

![image](https://github.com/bscan/PerlNavigator/assets/89495599/e2673aa5-cca9-48ea-8174-4349406a119a)
![image](https://github.com/bscan/PerlNavigator/assets/89495599/e36f3cfa-e189-468a-9aa5-1e4222e5b581)

**Comment by bscan** [comment]
Funny timing, I was actually just working on this feature #24 . With the new parser I added last week (parser.ts), many more features that require parsing code are now possible. `signatures.ts` contains most of the relevant code, plus some modifications to parser.ts. Call signatures now show up when typing signatures and when hovering over the subroutine itself. There's a little more work I'd like to do before releasing this to vscode and npm, especially around caching parsing results. A review would certainly be helpful if you're interested. Thanks! 

![image](https://github.com/bscan/PerlNavigator/assets/10503608/79d81845-ac34-44e5-ae34-b5e84db10ad6)

![image](https://github.com/bscan/PerlNavigator/assets/10503608/238aa789-d06f-4d8e-8726-688c6922ee66)

**Comment by bscan** [comment]
This feature seems to be fairly stable now. Thanks!
